name: Reel-AI
options:
  bundleIdPrefix: gauntletai
  deploymentTarget:
    iOS: 16.0
packages:
  Appwrite:
    url: https://github.com/appwrite/sdk-for-apple
    from: 4.0.0
  AnyCodable:
    url: https://github.com/Flight-School/AnyCodable
    from: 0.6.7
  MuxSDK:
    url: https://github.com/muxinc/mux-stats-sdk-avplayer.git
    from: 3.1.0
schemes:
  Reel-AI:
    build:
      targets:
        Reel-AI: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  Reel-AI:
    type: application
    platform: iOS
    sources:
      - path: Reel-AI
        excludes:
          - "AnyCodable.swift"
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: gauntletai.Reel-AI
        DEVELOPMENT_TEAM: JAAQKRTXQ6
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: 1,2
    dependencies:
      - package: Appwrite
        product: Appwrite
      - package: AnyCodable
        product: AnyCodable
      - package: MuxSDK
        product: MUXSDKStats